language: vi
pipeline:
  - name: SpacyNLP
    model: "vi_spacy_model"
    case_sensitive: true
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: word
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 200
  - name: EntitySynonymMapper

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MappingPolicy
  - name: FallbackPolicy
    nlu_threshold: 0.7
    core_threshold: 0.7
    fallback_action_name: "action_unknown"