language: vi

pipeline:
  - name: SpacyNLP
    model: "vi_spacy_model"
    case_sensitive: true
  - name: SpacyTokenizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: word
    min_ngram: 1
    max_ngram: 4
  - name: rasa_nlu_examples.featurizers.dense.BytePairFeaturizer
    lang: vi
    vs: 200000
    dim: 300
  - name: DIETClassifier
    epochs: 300
    constrain_similarities: true
    model_confidence: softmax
  - name: EntitySynonymMapper
policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true
    model_confidence: softmax
  - name: FallbackPolicy
    nlu_threshold: 0.5
    core_threshold: 0.5
    fallback_action_name: "action_unknown"